### ISSUE TITLE
ReferenceError: CLEANUP is not defined

### ISSUE THREAD

**Issue by pkopach** [petersirka/nosql#28]
Hi!
I try use nosql v 4.0.0. When i try load nosql database:
```
var NoSQL = require("nosql");
var db = NoSQL.load("file.nosql");
```
i receive next error:
```
ReferenceError: CLEANUP is not defined
    at Database.$reader2 (/project/node_modules/total.js/nosql.js:546:2)
    at Database.$reader (/project/node_modules/total.js/nosql.js:459:7)
    at Database.next (/project/node_modules/total.js/nosql.js:259:8)
    at tryOnImmediate (timers.js:554:5)
    at processImmediate [as _immediateCallback] (timers.js:533:5)
```

**Comment by petersirka** [comment]
Hi @pkopach,
I have fixed it. Thank you!

`npm install nosql`
