### ISSUE TITLE
Error when running an application

### ISSUE THREAD

**Issue by dustinaevans** [petersirka/nosql#41]
/applications/<applicationName>/server/node_modules/nosql/index.js:29
const Fs = require('fs');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/applications/<applicationName>/server/server.js:3:11)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by petersirka** [comment]
Hi @dustinaevans, sorry for delay. Which version of Node.js do you use?

**Comment by dustinaevans** [comment]
3.10.10

**Comment by petersirka** [comment]
It's too old. You need to use v4/6 or v8.
